-- Twenty more fictional investors for demos. Emails route to test aliases; phones use reserved ranges.
insert into public.investors
  (full_name, title, firm, email, phone, location, investor_type, stages, sectors,
   check_min_usd, check_max_usd, fund_size_usd, portfolio, thesis, "values",
   focus_note, leads_rounds, min_revenue_band, website_url)
values
  ('Amara Osei', 'Partner', 'Foundry Row Capital', 'oliverburt3+11@gmail.com', '+44 7700 900111',
   'London, UK', 'vc', '{seed,series_a}', '{hardware,ecommerce,logistics}', 500000, 2500000, 140000000,
   '{Crateworks,Pallo,"Shelf Nine"}', 'Physical products with software attached. Wants gross margin above 40% by Series A.',
   '{}', 'B2B physical products only', true, '21_30k', 'https://foundryrow.example'),
  ('Lucas Brandt', 'Principal', 'Nordlicht Ventures', 'oliverburt3+12@gmail.com', '+44 7700 900112',
   'Berlin, DE', 'vc', '{pre_seed,seed}', '{b2b_saas,ai_ml,devtools}', 200000, 800000, 90000000,
   '{Queryline,Stackwise,"Loom Labs"}', 'Developer-led software with bottom-up adoption in Europe.',
   '{open_source}', 'Prefers product-led growth', true, null, 'https://nordlicht.example'),
  ('Grace Whitfield', 'Angel investor', 'Independent', 'oliverburt3+13@gmail.com', '+44 7700 900113',
   'Oxford, UK', 'angel', '{angel,pre_seed}', '{health,edtech}', 15000, 60000, null,
   '{Tutorwise,Clearpath}', 'Former NHS operations lead. Backs founders fixing broken public service workflows.',
   '{social_impact,health_wellbeing}', 'Health and education only', false, null, null),
  ('Ravi Menon', 'General Partner', 'Tidewater Capital', 'oliverburt3+14@gmail.com', '+1 555 0114',
   'New York, US', 'vc', '{series_a,series_b}', '{fintech,b2b_saas}', 2000000, 8000000, 400000000,
   '{Ledgerbase,Paystream,Clearrate}', 'Infrastructure for finance teams. Needs $1m ARR before a first meeting.',
   '{}', 'Revenue-first, $1m ARR minimum', true, '51_100k', 'https://tidewater.example'),
  ('Chloe Martin', 'Investment Manager', 'Verdant Seed Fund', 'oliverburt3+15@gmail.com', '+44 7700 900115',
   'Bristol, UK', 'vc', '{pre_seed,seed}', '{climate,food_agri,consumer}', 100000, 500000, 45000000,
   '{Rootbox,Refillery,Compostly}', 'Consumer and food brands that cut waste. Likes refill and reuse models.',
   '{eco_friendly,b_corp}', 'Requires a waste or carbon metric', true, '0_10k', 'https://verdant.example'),
  ('Hiro Tanaka', 'Head of Investments', 'Kaizen Industrial Ventures', 'oliverburt3+16@gmail.com', '+1 555 0116',
   'San Jose, US', 'cvc', '{seed,series_a}', '{hardware,logistics,ai_ml}', 750000, 3000000, 220000000,
   '{Gripline,Palletbot,"Sensor Six"}', 'Corporate arm of a manufacturing group. Looks for factory-floor pilots.',
   '{}', 'Manufacturing and warehouse tech', false, '11_20k', 'https://kaizen-iv.example'),
  ('Isabel Costa', 'Partner', 'Mercado Ventures', 'oliverburt3+17@gmail.com', '+44 7700 900117',
   'Lisbon, PT', 'vc', '{seed}', '{marketplace,ecommerce,consumer}', 300000, 1200000, 75000000,
   '{Tradeloop,Stockr,Vendio}', 'B2B marketplaces with repeat buyers and take rates above 8%.',
   '{}', 'Marketplaces with proven liquidity', true, '11_20k', 'https://mercado.example'),
  ('Owen Price', 'Angel investor', 'Independent', 'oliverburt3+18@gmail.com', '+44 7700 900118',
   'Cardiff, UK', 'angel', '{angel,pre_seed,seed}', '{hardware,ecommerce,gtm_sales}', 20000, 75000, null,
   '{Kitchenly,Boxfold}', 'Built and sold a packaging business. Helps with suppliers, retail buyers and pricing.',
   '{local_community}', 'Physical products and retail', false, '0_10k', null),
  ('Nadia Rahman', 'Principal', 'Horizon Health Partners', 'oliverburt3+19@gmail.com', '+44 7700 900119',
   'Manchester, UK', 'vc', '{seed,series_a}', '{health,ai_ml}', 500000, 2000000, 160000000,
   '{Carepath,Dosewise,Triage One}', 'Clinical workflow software with NHS or payer validation.',
   '{health_wellbeing,ethical_ai}', 'Needs a clinical pilot', true, '11_20k', 'https://horizonhealth.example'),
  ('Ben Carter', 'Founding Partner', 'Anvil Pre-Seed', 'oliverburt3+20@gmail.com', '+44 7700 900120',
   'London, UK', 'vc', '{pre_seed}', '{b2b_saas,gtm_sales,marketplace,hardware}', 100000, 350000, 30000000,
   '{Signalroom,Quotebench,Fixr}', 'First institutional cheque into repeat founders and ex-operators.',
   '{diversity}', 'Writes the first cheque', true, 'pre_revenue', 'https://anvil.example'),
  ('Sophie Laurent', 'Investment Director', 'Seine Impact', 'oliverburt3+21@gmail.com', '+44 7700 900121',
   'Paris, FR', 'vc', '{seed,series_a}', '{climate,edtech,health}', 700000, 3000000, 180000000,
   '{Solarly,Classnote,"Air Nine"}', 'Measurable social and environmental outcomes, audited annually.',
   '{social_impact,b_corp,eco_friendly}', 'Impact reporting required', true, '11_20k', 'https://seineimpact.example'),
  ('Marco Bellini', 'Partner', 'Bellini Family Office', 'oliverburt3+22@gmail.com', '+44 7700 900122',
   'Milan, IT', 'family_office', '{seed,series_a,series_b}', '{consumer,food_agri,ecommerce}', 250000, 2000000, 500000000,
   '{Oliveto,Pastaio,"Casa Nova"}', 'Long-horizon capital for consumer brands with European distribution.',
   '{local_community}', 'Consumer brands with retail presence', false, '31_50k', null),
  ('Tariq Aziz', 'Partner', 'Gulfstream Tech Fund', 'oliverburt3+23@gmail.com', '+1 555 0123',
   'Austin, US', 'vc', '{seed,series_a}', '{fintech,proptech,b2b_saas}', 500000, 2500000, 130000000,
   '{Rentline,Titlebase,Escrowly}', 'Software for property and lending workflows that are still run on email.',
   '{}', 'Vertical software', true, '21_30k', 'https://gulfstream.example'),
  ('Emily Zhang', 'Scout', 'Brightwater Partners', 'oliverburt3+24@gmail.com', '+1 555 0124',
   'San Francisco, US', 'angel', '{angel,pre_seed}', '{ai_ml,devtools}', 10000, 50000, null,
   '{Promptly Labs,Evalkit}', 'Scout cheques for technical founders, with a path to a Brightwater seed.',
   '{open_source,ethical_ai}', 'Technical founders only', false, null, null),
  ('Patrick Doyle', 'Managing Partner', 'Harbour Lane Capital', 'oliverburt3+25@gmail.com', '+44 7700 900125',
   'Dublin, IE', 'vc', '{seed,series_a}', '{b2b_saas,gtm_sales,fintech}', 400000, 2000000, 110000000,
   '{Revline,Dealdesk,Billstack}', 'Revenue software for mid-market sales teams.',
   '{}', 'Sales, RevOps and billing tools', true, '11_20k', 'https://harbourlane.example'),
  ('Aisha Bello', 'Programme Director', 'Launchpad North', 'oliverburt3+26@gmail.com', '+44 7700 900126',
   'Leeds, UK', 'accelerator', '{pre_seed}', '{b2b_saas,consumer,edtech,hardware}', 25000, 100000, 12000000,
   '{Stitchly,Quizbox,Boltware}', 'Ten week programme for founders outside London. $60k for 6%.',
   '{diversity,local_community}', 'Founders based outside London', true, 'pre_revenue', 'https://launchpadnorth.example'),
  ('Henrik Olsen', 'Partner', 'Fjord Climate Capital', 'oliverburt3+27@gmail.com', '+44 7700 900127',
   'Oslo, NO', 'vc', '{seed,series_a,series_b}', '{climate,hardware,logistics}', 1000000, 5000000, 350000000,
   '{Heatwell,Grid North,"Battery Bay"}', 'Hardware-heavy decarbonisation with a path to project finance.',
   '{eco_friendly}', 'Energy and heavy industry', true, '21_30k', 'https://fjordclimate.example'),
  ('Laura Kim', 'Angel investor', 'Independent', 'oliverburt3+28@gmail.com', '+1 555 0128',
   'Seattle, US', 'angel', '{angel,pre_seed,seed}', '{marketplace,consumer,ecommerce}', 25000, 100000, null,
   '{Thriftly,Sizewise}', 'Former marketplace operator. Helps with supply acquisition and unit economics.',
   '{}', 'Marketplaces and DTC', false, '0_10k', null),
  ('Daniel Okoro', 'Associate', 'Keel Street Capital', 'oliverburt3+29@gmail.com', '+1 555 0129',
   'Austin, US', 'vc', '{pre_seed,seed}', '{fintech,gtm_sales}', 250000, 1000000, 110000000,
   '{"Settle Stack","Pipeline Pilot"}', 'Sources pre-seed deals for Keel Street in vertical fintech.',
   '{diversity}', 'Remote-first teams', false, null, 'https://keelstreet.example'),
  ('Freya Lund', 'Partner', 'Northwind Industrial Fund', 'oliverburt3+30@gmail.com', '+44 7700 900130',
   'Copenhagen, DK', 'vc', '{seed,series_a}', '{hardware,logistics,food_agri}', 600000, 3000000, 190000000,
   '{Coldloop,Packwise,"Harvest Grid"}', 'Supply chain hardware and the software that runs it.',
   '{eco_friendly}', 'Needs a signed pilot customer', true, '11_20k', 'https://northwindif.example');
